title = "FastTrack cfg"

[parameters]
lightBack = 1
maxArea = 5000 
maxDist = 50
maxTime = 100
methBack = 1
minArea = 100
normAngle = 2
normArea = 1
normDist = 1
normPerim = 0
reg = 0
spot = 2
xBottom = 0
xTop = 0
yBottom = 0
yTop = 0
