title = "FastTrack cfg"

[parameters]
lightBack = 1
maxArea = 5000
maxDist = 50
maxTime = 100
methBack = 1
minArea = 100
normAngle = 3
normArea = 2
normDist = 1
normPerim = 0
reg = 0
xBottom = 0
xTop = 0
yBottom = 0
yTop = 0
